yarnPath: '.yarn/releases/yarn-berry.cjs'
nodeLinker: 'node-modules'

packageExtensions:
  '@react-navigation/native@*':
    peerDependencies:
      react: '*'
      react-native: '*'
  'react-native-animated-nav-tab-bar@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
